# Generated by Django 3.0.3 on 2020-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20200409_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('product_image', models.ImageField(blank=True, upload_to='product_images')),
                ('product_cost', models.IntegerField()),
                ('product_available', models.BooleanField()),
            ],
        ),
    ]
