# Generated by Django 3.0.3 on 2020-04-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_available',
            field=models.BooleanField(null=True),
        ),
    ]
