# Generated by Django 3.0.3 on 2020-04-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='user',
        ),
    ]
