# Generated by Django 3.0.3 on 2020-04-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_auto_20200411_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
